Repository doka-guide/platform, pull requests merged in 2021-06, with the labels that each got.

#203 Добавляет переменную для обозначения последнего редактирования статьи
  .eleventy.js
  src/layouts/article.njk
Labels: кухня

#194 Чинит оглавление
  .eleventy.js
  src/includes/blocks/aside.njk
  src/includes/collections.njk
  src/includes/collections/css-articles-list.njk
  src/includes/collections/css-articles.njk
  src/includes/collections/css-doka-list.njk
  src/includes/collections/html-articles-list.njk
  src/includes/collections/html-articles.njk
  src/includes/collections/html-doka-list.njk
  src/includes/collections/js-articles-list.njk
  src/includes/collections/js-articles.njk
  src/includes/collections/js-doka-list.njk
  src/includes/collections/tools-articles-list.njk
  src/includes/collections/tools-articles.njk
  src/includes/collections/tools-doka-list.njk
  src/layouts/article.njk
  src/pages/all.njk
Labels: движок, ошибка

#204 Штуки для поиска и SEO
  .eleventy.js
  src/pages/sitemap.xml.njk
  src/robots.txt
Labels: улучшение

#213 Меняет способ установки зависимостей на `npm ci` в Dockerfile
  Dockerfile
Labels: кухня

#215 Исправляет карту сайта
  .eleventy.js
  src/sitemap.njk
Labels: кухня, ошибка

#202 Попытка оптимизации
  .github/workflows/netlify-deploy.yml
  package-lock.json
  package.json
Labels: кухня

#210 Добавляет линтинг на precommit-хук
  .eslintrc.json
  .stylelintrc.json
  package-lock.json
  package.json
Labels: кухня
