Repository doka-guide/platform, pull requests merged in 2021-10, with the labels that each got.

#469 Убирает `title` со ссылок на зафичеренных статьях на главной
  src/includes/blocks/featured-article.njk
Labels: улучшение

#477 Добавляет фильтр для валидатора
  package.json
Labels: ошибка, кухня

#690 Обновляет Node.js до 16
  .github/workflows/linting.yml
  .github/workflows/surge-preview.yml
  .github/workflows/w3c-validator.yml
  .nvmrc
  Dockerfile
  package-lock.json
  package.json
Labels: кухня
