Repository doka-guide/platform, pull requests merged in 2021-12, with the labels that each got.

#765 Улучшения для блоков кода
  src/scripts/index.js
  src/scripts/modules/copy-code-snippet.js
  src/styles/blocks/block-code.css
  src/styles/blocks/copy-button.css
  src/styles/index.css
  src/transforms/code-transform.js
Labels: улучшение, вопрос, движок, дизайн

#700 Правки логики отправки формы обратной связи
  src/includes/feedback-form.njk
  src/scripts/index.js
  src/scripts/modules/feedback-form.js
  src/views/doc.njk
Labels: улучшение

#776 Правит моменты появления/исчезновения шапки при скролле
  src/scripts/libs/throttle.js
  src/scripts/modules/header.js
  src/styles/blocks/header.css
Labels: улучшение, вопрос, вёрстка, дизайн

#811 Правки manifest.json и добавил maskable иконку
  src/images/icons/maskable.png
  src/manifest.json
Labels: улучшение, вёрстка

#816 Добавляет дополнительные условия показа/скрытия шапки
  src/scripts/modules/article-aside.js
  src/scripts/modules/header.js
Labels: улучшение, вёрстка, дизайн

#823 Фиксит старый бейдж, добавляет новый
  README.md
Labels: кухня

#831 Удаляет подсветку при tap для кнопки содержания
  src/styles/blocks/article-nav.css
Labels: улучшение, вёрстка, дизайн

#834 Фиксит по EditorConfig
  src/transforms/details-transform.js
  src/transforms/image-place-transform.js
Labels: улучшение, кухня

#837 Игнорирует преобразование изображений уже находящихся внутри picture
  src/transforms/image-transform.js
Labels: улучшение, движок, автоматизация

#847 Добавляет снег ❄️
  src/includes/blocks/footer.njk
  src/includes/blocks/snow-toggle.njk
  src/includes/blocks/snow.njk
  src/layouts/base.njk
  src/scripts/index.js
  src/scripts/modules/snow-toggle.js
  src/styles/blocks/snow-toggle.css
  src/styles/blocks/snow.css
  src/styles/index.css
Labels: улучшение

#849 Раскидывает снежок на всю ширину
  src/styles/blocks/snow.css
Labels: кухня

#853 Фиксит снег
  src/includes/blocks/snow-toggle.njk
  src/layouts/base.njk
  src/scripts/modules/snow-toggle.js
  src/styles/blocks/snow.css
Labels: кухня
