Repository doka-guide/platform, pull requests merged in 2021-07, with the labels that each got.

#216 Добавляет экшн для сборки образа
  .github/workflows/docker-deploy.yml
  README.md
Labels: кухня, улучшение

#245 Правит адрес электронной почты
  src/includes/feedback-form.njk
Labels: кухня

#255 Правит скрипт для путей
  .eleventy.js
Labels: движок, ошибка

#211 Добавляет dev-режим работы c CSS и JS без пересборки eleventy
  .eleventy.js
  .eleventyignore
Labels: кухня

#239 Вывод даты последнего редактирования статьи
  .eleventy.js
  .eslintrc.json
  .gitignore
  src/scripts/index.js
  src/scripts/modules/last-update.js
  src/views/doc.11tydata.js
  src/views/doc.njk
Labels: движок

#271 Предотвращает падение сборки, если нет поля `updatedAt`
  src/views/doc.11tydata.js
  src/views/doc.njk
Labels: движок, кухня, ошибка

#273 Исключает файлы индексов категорий из коллекции статей
  .eleventy.js
Labels: движок, кухня

#272 CSS-правила для шрифтов и цветов
  .stylelintrc.json
  src/styles/blocks/theme.css
Labels: вёрстка, дизайн

#276 Добавляет вывод обложек для статей
  src/views/doc.njk
Labels: движок, ошибка

#269 Добавляет тестовую сборку сайта при PR
  .github/workflows/build-test.yml
Labels: кухня, тестирование

#277 Добавляет метрику
  src/includes/analytics/metrika.njk
  src/layouts/base.njk
Labels: кухня

#279 Добавляет якоря для мнений авторов
  src/includes/practices.njk
Labels: движок

#282 Добавляет хеширование для файлов CSS и JS для инвалидации кэша
  gulpfile.js
  package-lock.json
  package.json
Labels: движок, кухня
