Repository doka-guide/platform, pull requests merged in 2021-11, with the labels that each got.

#703 Упрощает CSS-селекторы для шапки
  src/styles/blocks/header.css
Labels: вёрстка

#716 Переименовывает раздел «В работе» в «На практике»
  src/includes/practices.njk
  src/transforms/demo-link-transform.js
Labels: кухня

#724 Реализация деплоя
  .github/workflows/product-deploy.yml
  README.md
  docs/deploy.md
  package.json
  src/views/doc.njk
Labels: улучшение, кухня

#730 Меняет переменные окружения и фиксит деплой
  .env
  .github/workflows/product-deploy.yml
  package.json
Labels: ошибка, кухня, автоматизация

#732 Меняет относительный путь
  package.json
Labels: ошибка, кухня, автоматизация

#733 Исправляет кавычки
  package.json
Labels: ошибка, кухня, автоматизация

#729 Рефактор header в виде компонента
  src/includes/blocks/header.njk
  src/scripts/index.js
  src/scripts/modules/article-aside.js
  src/scripts/modules/header.js
  src/styles/blocks/article.css
Labels: улучшение, вёрстка, js

#728 Увеличивает контрастность переключателя темы
  src/styles/blocks/theme-toggle.css
Labels: вёрстка, дизайн

#739 Правки сборки для Windows
  .eleventy.js
  make-links.js
Labels: ошибка, улучшение, движок

#734 Отпиливает всё про Netlify
  .dockerignore
  README.md
  docs/deps.md
  netlify.toml
  package-lock.json
  src/includes/feedback-form.njk
Labels: кухня

#712 Добавляет ширину блоку details
  src/styles/blocks/content.css
Labels: вёрстка, дизайн

#707 Делает тень под шапкой более гладкой (#706)
  src/styles/blocks/header.css
Labels: улучшение, вёрстка

#760 Добавляет атрибуты `rel="noopener" rel="noreferrer"` для внешних ссылок на github на странице статьи
  src/views/doc.njk
Labels: улучшение

#767 Добавляет поправку на параметр
  src/robots.txt
Labels: улучшение, кухня

#759 Сохранение фильтра в url на странице индексов статей
  src/layouts/base.njk
  src/scripts/modules/articles-index.js
  src/styles/blocks/index-section.css
  src/views/article-index.njk
Labels: улучшение

#749 Добавляет поддержку клавиатуры в быстром поиске
  src/includes/blocks/search.njk
  src/scripts/modules/quick-search.js
  src/styles/blocks/search.css
  src/styles/blocks/suggestion-list.css
Labels: улучшение, вопрос, дизайн

#768 Добавляет метки к ссылке на Практикум
  src/includes/blocks/footer.njk
Labels: кухня
