Repository doka-guide/platform, pull requests merged in 2021-09, with the labels that each got.

#313 Улучшает превью
  .github/workflows/surge-preview.yml
Labels: улучшение

#315 Добавляет отступы для прокрутки до якорей заголовков
  src/styles/blocks/article-heading.css
Labels: улучшение

#332 Добавляет валидатор w3c
  .github/workflows/surge-preview.yml
  .github/workflows/w3c-validator.yml
  README.md
Labels: кухня, тестирование

#333 Добавляет линтеры JS/CSS на основе базовых правил
  .github/workflows/linting.yml
Labels: кухня, тестирование

#316 Вывод результатов поиска
  .eleventy.js
  gulpfile.js
  package-lock.json
  package.json
  src/images/edit-icon.svg
  src/includes/blocks/header.njk
  src/includes/blocks/search-category.njk
  src/includes/blocks/search-hits.njk
  src/includes/blocks/search-tags.njk
  src/includes/blocks/search.njk
  src/scripts/index.js
  src/scripts/modules/header.js
  src/scripts/modules/search-page-filter.js
  src/scripts/modules/search.js
  src/styles/blocks/breadcrumbs.css
  src/styles/blocks/header.css
  src/styles/blocks/search-category.css
  src/styles/blocks/search-hit.css
  src/styles/blocks/search-page.css
  src/styles/blocks/search-section.css
  src/styles/blocks/search-tag.css
  src/styles/blocks/search.css
  src/styles/blocks/tag.css
  src/styles/index.css
  src/views/search.njk
Labels: улучшение, кухня

#381 Обновляет зависимости
  package-lock.json
  package.json
Labels: кухня

#386 Раскоменчивает вывод зафичеренных статей
  src/views/index.11tydata.js
Labels: улучшение, кухня

#435 Вносит минорные лит. правки в документацию
  README.md
  docs/deploy.md
  docs/deps.md
  docs/how-to-run.md
Labels: кухня

#443 Исправляет ошибку с глобальной переменной
  src/layouts/base.njk
Labels: ошибка, движок

#444 Добавляет тэг Google Analytics
  src/includes/analytics/google.njk
  src/layouts/base.njk
Labels: улучшение, кухня
