Repository doka-guide/platform, pull requests merged in 2021-08, with the labels that each got.

#263 Замена img на picture внутри контента
  .eleventy.js
  .eslintignore
  package-lock.json
  package.json
Labels: улучшение, движок

#290 Добавляет cross-env
  package-lock.json
  package.json
Labels: улучшение, кухня, движок

#293 Создаёт экшен для превью сайта
  .github/workflows/build-test.yml
  .github/workflows/surge-preview.yml
Labels: кухня, тестирование

#285 Добавляет расчёт времени чтения статьи
  .eleventy.js
  src/views/doc.njk
Labels: улучшение

#303 Добавляет фильтр для копирования файлов демок
  .eleventy.js
Labels: улучшение, кухня, движок
