Repository doka-guide/platform, pull requests merged in 2022-09, with the labels that each got.

#973 Новые карточки на главной
  src/images/partners/practicum.svg
  src/includes/blocks/footer.njk
  src/styles/blocks/intro.css
  src/views/index.njk
Labels: вёрстка, дизайн

#977 Скругляет обводку переключателей цветовой темы
  src/styles/blocks/theme-toggle.css
Labels: улучшение, вёрстка

#975 Упрощает стиль переключателя фильтра поиска
  src/styles/blocks/switch.css
Labels: улучшение, вёрстка

#974 Рефакторит вычисление последнего времени обновления #206
  src/scripts/modules/last-update.js
Labels: улучшение, движок

#958 Изменяет дизайн совета
  src/includes/practices.njk
  src/scripts/index.js
  src/scripts/modules/practices.js
  src/styles/blocks/details.css
  src/styles/blocks/header.css
  src/styles/blocks/practices.css
  src/styles/index.css
  src/transforms/toc-transform.js
  src/views/doc.11tydata.js
Labels: вёрстка, дизайн

#956 Изменяет дизайн хедера
  src/includes/blocks/header.njk
  src/includes/blocks/logo.njk
  src/scripts/modules/header.js
  src/scripts/modules/logo.js
  src/scripts/modules/quick-search.js
  src/scripts/modules/search.js
  src/styles/blocks/header.css
  src/styles/blocks/logo.css
  src/styles/blocks/menu-toggle.css
  src/styles/blocks/nav-list.css
  src/styles/blocks/search-page.css
  src/styles/blocks/search.css
  src/views/404.njk
  src/views/index.njk
  src/views/people.njk
  src/views/person.njk
  src/views/views.11tydata.js
Labels: вёрстка, дизайн
