Repository doka-guide/platform, pull requests merged in 2022-10, with the labels that each got.

#983 Изменяет переносы слов-названий методов в тексте
  src/transforms/code-breakify-transform.js
Labels: улучшение, движок

#989 Правит нейминг классов
  src/includes/articles-gallery.njk
  src/includes/related-articles-gallery.njk
  src/scripts/modules/articles-gallery.js
  src/styles/blocks/featured-articles-list.css
  src/styles/index.css
  src/styles/index.sc.css
Labels: ошибка, вёрстка

#998 Правит переносы имён методов
  src/transforms/code-breakify-transform.js
Labels: ошибка

#999 Приводит названия к единому шаблону
  src/markdown-it.js
  src/transforms/article-code-blocks-transform.js
Labels: ошибка, движок

#995 Добавляет поддержку ссылок на Telegram для страницы автора
  src/views/person.11tydata.js
  src/views/person.njk
Labels: улучшение, вёрстка, дизайн

#996 Добавляет превью цвета в блоках кода
  .eleventy.js
  src/styles/blocks/color-picker.css
  src/styles/code-dark-theme.css
  src/styles/code-light-theme.css
  src/styles/index.css
  src/transforms/color-picker-transform.js
Labels: улучшение, движок

#1002 Оставляет только один тип карточки для Твиттера
  src/includes/meta.njk
Labels: улучшение

#1003 Правит ошибки превью цвета в блоках кода
  src/styles/blocks/color-picker.css
  src/transforms/color-picker-transform.js
Labels: улучшение

#1011 Добавляет раздел Доступность
  .eleventy.js
  .env.example
  .eslintignore
  config/category-colors.js
  config/constants.js
  gulpfile.js
  src/styles/base-colors.css
  src/styles/blocks/logo.css
  src/styles/dark-theme.css
  src/styles/light-theme.css
Labels: кухня, вёрстка, дизайн

#1010 Меняет эмоджи напротив «Участники»
  src/views/index.njk
Labels: улучшение, дизайн

#1005 Обновляет анимацию лого
  src/scripts/modules/logo.js
  src/styles/blocks/logo.css
Labels: улучшение, дизайн

#1013 Добавляет поддержку анимации лого в расширенном поиске
  src/scripts/modules/logo.js
Labels: улучшение, вёрстка, дизайн

#986 Добавляет рубрику «На собесе»
  .eleventy.js
  .env.example
  .gitignore
  config/constants.js
  src/images/partners/praktikum-icon.svg
  src/includes/blocks/person.njk
  src/includes/questions.njk
  src/libs/heading-hierarchy/heading-hierarchy.js
  src/libs/role-constructor/collection.json
  src/scripts/index.js
  src/scripts/modules/answer.js
  src/styles/blocks/answer.css
  src/styles/blocks/article-heading.css
  src/styles/blocks/callout.css
  src/styles/blocks/person-page.css
  src/styles/blocks/questions.css
  src/styles/blocks/toc.css
  src/styles/index.css
  src/transforms/answers-link-transform.js
  src/transforms/headings-anchor-transform.js
  src/transforms/headings-id-transform.js
  src/transforms/toc-transform.js
  src/views/doc.11tydata.js
  src/views/doc.njk
  src/views/people.njk
  src/views/person.11tydata.js
  src/views/person.njk
  src/views/views.11tydata.js
Labels: улучшение, вёрстка, движок, дизайн

#1017 Хотфикс с трансформацией
  src/transforms/answers-link-transform.js
Labels: ошибка

#1018 Обрезает длинный заголовок в боковом меню
  src/scripts/index.js
  src/scripts/modules/toc-text-crop.js
Labels: улучшение, кухня

#1019 Добавляет конфиг тестов
  .eslintrc.json
  README.md
  jest.config.js
  package-lock.json
  package.json
  src/scripts/libs/__tests__/example.js
Labels: кухня

#1026 Исправляет список статей с ответами участника
  src/views/views.11tydata.js
Labels: ошибка

#993 Добавляет значки для авторов
  .eleventy.js
  src/images/badges/doka-dog-help-10.svg
  src/images/badges/doka-dog-help-100.svg
  src/images/badges/doka-dog-help-5.svg
  src/images/badges/doka-dog-help-50.svg
  src/images/badges/first-contribution-small.svg
  src/images/badges/merged-pr-10.svg
  src/images/badges/merged-pr-100.svg
  src/images/badges/merged-pr-5.svg
  src/images/badges/merged-pr-50.svg
  src/images/badges/most-viewed-month-line.svg
  src/images/badges/most-viewed-month-zeta.svg
  src/images/badges/most-viewed-week-line.svg
  src/images/badges/most-viewed-week-zeta.svg
  src/images/badges/most-viewed-year-line.svg
  src/images/badges/most-viewed-year-zeta.svg
  src/includes/blocks/person-badges.njk
  src/libs/badge-constructor/badge-constructor.js
  src/libs/badge-constructor/collection.json
  src/libs/github-contribution-service/github-contribution-service.js
  src/scripts/index.js
  src/scripts/modules/person-badges-tooltip.js
  src/scripts/modules/person-badges.js
  src/styles/blocks/person-badges.css
  src/styles/blocks/person-page.css
  src/styles/index.css
  src/views/person-json.11tydata.js
  src/views/person-json.njk
  src/views/person.11tydata.js
  src/views/person.njk
  src/views/views.11tydata.js
Labels: улучшение, вёрстка, дизайн

#1028 [На собеседовании] Меняет ссылку на инструкцию
  src/includes/questions.njk
Labels: улучшение, кухня
