Repository doka-guide/platform, pull requests merged in 2022-07, with the labels that each got.

#947 Убирает скролл на странице поиска (doka-guide/platform#939)
  src/styles/blocks/search-page.css
  src/styles/blocks/search.css
Labels: улучшение, дизайн

#949 Добавляет советы в список материалов участника
  src/includes/blocks/person.njk
  src/views/people.njk
  src/views/person.11tydata.js
  src/views/person.njk
  src/views/views.11tydata.js
Labels: улучшение

#950 Делает вторую версию карточек для соц. сетей
  gulpfile.js
  src/includes/blocks/social-card.njk
  src/includes/meta.njk
  src/styles/blocks/social-card.css
  src/views/sc.11tydata.js
  src/views/sc.njk
Labels: улучшение

#954 Фиксит ссылку в шапке на странице участников
  src/views/people.njk
Labels: ошибка, улучшение
