Repository doka-guide/platform, pull requests merged in 2022-08, with the labels that each got.

#964 Чинит пути к картинкам
  src/includes/blocks/social-card.njk
Labels: ошибка, автоматизация

#966 Исправляет никнеймы для twitter и behance
  src/views/person.11tydata.js
  src/views/person.njk
Labels: ошибка, кухня

#967 Чинит заголовок карточки рекомендаций
  src/styles/blocks/featured-article.css
Labels: вёрстка

#968 Добавляет форму для отправки вопросов
  src/scripts/index.js
  src/scripts/modules/question-form.js
  src/styles/blocks/question-form.css
  src/styles/index.css
Labels: вёрстка, движок, дизайн

#969 Добавляет инструкцию для фикса проблемы с загрузкой
  README.md
  docs/README.md
  docs/load-fix.md
Labels: кухня

#970 Убирает скругление поля на iOS
  src/styles/blocks/text-control.css
Labels: улучшение, вёрстка
