Repository doka-guide/platform, pull requests merged in 2022-05, with the labels that each got.

#925 Реализует возможность просмотра только одной статьи
  make-links.js
Labels: улучшение, кухня

#807 Добавляет страницы для людей
  .eleventy.js
  .gitignore
  docs/how-to-run.md
  package-lock.json
  package.json
  src/includes/blocks/article-image.njk
  src/includes/blocks/header.njk
  src/includes/blocks/person-avatar.njk
  src/includes/blocks/person.njk
  src/includes/contributors.njk
  src/includes/practices.njk
  src/libs/github-contribution-service/github-contribution-service.js
  src/scripts/index.js
  src/scripts/modules/filter-panel.js
  src/scripts/modules/people.js
  src/styles/blocks/articles-group.css
  src/styles/blocks/filter-group.css
  src/styles/blocks/filter-panel.css
  src/styles/blocks/float-button.css
  src/styles/blocks/people-page.css
  src/styles/blocks/person-avatar.css
  src/styles/blocks/person-grid.css
  src/styles/blocks/person-links-list.css
  src/styles/blocks/person-page.css
  src/styles/blocks/person.css
  src/styles/blocks/tag-filter.css
  src/styles/index.css
  src/views/article-index.njk
  src/views/doc.njk
  src/views/people.11tydata.js
  src/views/people.njk
  src/views/person.11tydata.js
  src/views/person.njk
  src/views/views.11tydata.js
Labels: улучшение, вопрос, кухня, вёрстка, движок, дизайн

#931 Исправляет проблему с аватарами участников
  .eleventy.js
  src/views/views.11tydata.js
Labels: ошибка, вёрстка, движок

#929 Отображает список подкатегорий в представлении статей по алфавиту
  .eleventy.js
  src/styles/blocks/articles-group.css
  src/views/article-index.11tydata.js
  src/views/article-index.njk
Labels: улучшение, вёрстка

#933 Перекрашивает иконку Behance
  src/views/person.njk
Labels: дизайн
