Repository doka-guide/platform, pull requests merged in 2022-01, with the labels that each got.

#858 Пробрасывает родительский контекст с данными в компонент `header`
  src/includes/blocks/header.njk
  src/views/404.njk
  src/views/all.njk
  src/views/article-index.njk
  src/views/doc.njk
  src/views/index.njk
  src/views/page.njk
  src/views/search.njk
Labels: движок

#839 Правит отображение featured-статей
  src/views/views.11tydata.js
Labels: движок

#846 Добавляет исключениe для rsync
  package.json
Labels: ошибка, кухня

#862 Обновляет зависимости
  package-lock.json
  package.json
Labels: кухня, движок

#857 Задаёт моноширинный шрифт для футера
  src/styles/blocks/footer.css
Labels: вёрстка, дизайн

#814 Фикс цвета комментариев в темной теме
  src/styles/code-dark-theme.css
  src/styles/code-light-theme.css
Labels: улучшение, вёрстка, дизайн

#803 Использует возможности Algolia для подсветки результатов
  src/scripts/core/search-commons.js
  src/scripts/modules/search.js
Labels: улучшение, вопрос, движок, поиск

#863 Подметает снег
  src/includes/blocks/footer.njk
  src/layouts/base.njk
  src/scripts/index.js
Labels: кухня

#850 Добавляет парсинг произвольного HTML в подписях изображений
  src/styles/blocks/figure.css
  src/transforms/code-transform.js
  src/transforms/image-place-transform.js
Labels: ошибка, вёрстка, движок, дизайн, автоматизация

#861 Правит высоту строк для текстовых блоков
  src/scripts/modules/search.js
  src/styles/blocks/article-heading.css
  src/styles/blocks/code-fix.css
  src/styles/index.css
  src/transforms/code-transform.js
Labels: вёрстка, дизайн

#875 Удаляет лишние файлы
  src/styles/box-sizing.css
  src/styles/pages/aside-page.css
  src/styles/pages/base.css
  src/styles/pages/index.css
Labels: вёрстка
