Repository doka-guide/platform, pull requests merged in 2022-06, with the labels that each got.

#935 Изменяет размеры заголовков четвёртого и пятого уровня
  src/styles/blocks/article-heading.css
  src/styles/blocks/font-theme.css
Labels: улучшение, вёрстка

#928 Заменяет Algolia на собственное решение
  package-lock.json
  package.json
  src/images/algolia-logo.svg
  src/scripts/core/search-api-client.js
  src/scripts/core/search-commons.js
  src/scripts/modules/quick-search.js
  src/scripts/modules/search.js
  src/styles/blocks/algolia-block.css
  src/styles/blocks/search-page.css
  src/styles/blocks/search.css
  src/styles/index.css
  src/views/search.njk
Labels: кухня, движок, поиск

#934 Преобразует текст после `<video>` в подпись
  .eleventy.js
  src/markdown-it.js
  src/styles/blocks/content.css
  src/styles/blocks/figure.css
  src/transforms/article-inline-code-transform.js
Labels: кухня, движок

#948 Удаляет метрики
  src/layouts/base.njk
Labels: кухня
