Repository doka-guide/platform, pull requests merged in 2022-02, with the labels that each got.

#870 Расставляет принудительные переносы в блоках кода
  .eleventy.js
  src/styles/blocks/code-fix.css
  src/styles/blocks/inline-code.css
  src/transforms/article-code-blocks-transform.js
  src/transforms/article-inline-code-transform.js
  src/transforms/code-breakify-transform.js
  src/transforms/code-classes-transform.js
Labels: вёрстка, дизайн, автоматизация

#884 Добавляет фикс для breakify угловых скобок
  src/transforms/code-breakify-transform.js
Labels: ошибка, вопрос, движок, автоматизация

#885 Правит селекторы в js-модуле расстановки номеров строк
  src/scripts/modules/code-line-numbers.js
Labels: вёрстка, движок

#887 Добавляет игнорирование преобразований для внешних изображений
  src/transforms/image-transform.js
Labels: движок

#866 Использует возможности Algolia для подсветки результатов
  src/scripts/core/search-commons.js
  src/scripts/modules/quick-search.js
  src/scripts/modules/search.js
Labels: вопрос, движок, дизайн, поиск

#896 Правит название Практикума под новые правила
  src/includes/blocks/footer.njk
Labels: кухня

#888 Добавляет возможность менять логотип в зависимости от страницы
  src/includes/blocks/header.njk
  src/includes/blocks/logo.njk
  src/views/404.njk
  src/views/views.11tydata.js
Labels: улучшение, вопрос, вёрстка, движок, дизайн

#904 Добавляет страницы событий / оферов
  .eleventy.js
  .env
  .eslintignore
  .gitignore
  src/views/sitemap.11tydata.js
  src/views/specials.11tydata.js
  src/views/specials.njk
Labels: улучшение, кухня, вёрстка
