Repository doka-guide/platform, pull requests merged in 2022-03, with the labels that each got.

#833 Добавляет ссылки на смежные статьи
  .eleventy.js
  src/includes/blocks/featured-article.njk
  src/includes/blocks/linked-article.njk
  src/includes/meta.njk
  src/includes/related-articles-gallery.njk
  src/scripts/index.js
  src/scripts/modules/articles-gallery.js
  src/scripts/modules/linked-article-navigation.js
  src/styles/blocks/articles-gallery.css
  src/styles/blocks/doc.css
  src/styles/blocks/linked-article.css
  src/styles/blocks/related-articles-list.css
  src/styles/index.css
  src/transforms/code-classes-transform.js
  src/views/article-index.11tydata.js
  src/views/doc.11tydata.js
  src/views/doc.njk
Labels: улучшение, вопрос, вёрстка, движок, дизайн

#897 Добавляет анимацию логотипа при поиске
  src/includes/blocks/logo.njk
  src/scripts/modules/header-quick-search-presenter.js
  src/scripts/modules/logo.js
  src/scripts/modules/search.js
  src/styles/base-colors.css
  src/styles/blocks/logo.css
  src/styles/dark-theme.css
  src/styles/light-theme.css
Labels: улучшение, вёрстка, дизайн

#892 Добавляет эффект hover для карточки статьи
  src/styles/blocks/featured-article.css
Labels: вёрстка, дизайн

#891 Добавляет перенос эмоджи в callout
  src/styles/blocks/callout.css
Labels: вёрстка, дизайн

#899 Удаляет обработку бектиков в теле поискового сниппета
  src/scripts/modules/search.js
Labels: улучшение, вопрос, кухня, движок, js, поиск

#882 Рефакторит работу с переменными окружения
  .env.example
  .github/workflows/product-deploy.yml
  .github/workflows/surge-preview.yml
  .gitignore
  Dockerfile
  README.md
  config/constants.js
  make-links.js
  package.json
  src/includes/articles-gallery.njk
  src/views/article-index.njk
  src/views/views.11tydata.js
Labels: вопрос, кухня, движок, автоматизация

#914 Обновляет CODEOWNER'ов
  CODEOWNERS
Labels: кухня

#916 Делает ссылки правильными
  .github/workflows/product-deploy.yml
Labels: ошибка

#917 Прибивает футер к низу
  src/styles/blocks/index-block.css
Labels: вёрстка

#913 Правит документацию по сборке проекта
  README.md
  docs/how-to-run.md
Labels: кухня

#911 Добавляет раздел Рецепты
  .eleventy.js
  .env.example
  .eslintignore
  .gitignore
  config/category-colors.js
  config/constants.js
  gulpfile.js
  package.json
  src/styles/base-colors.css
  src/styles/dark-theme.css
  src/styles/light-theme.css
Labels: улучшение, кухня
