Repository doka-guide/platform, pull requests merged in 2022-11, with the labels that each got.

#1030 Добавляет бейдж и ссылку на Дискорд
  README.md
Labels: кухня

#1032 Чинит врезки в текст
  src/styles/blocks/callout.css
Labels: ошибка, вёрстка, дизайн

#1034 Добавляет роль и значок для хакатона
  src/images/badges/hackathon-practicum.svg
  src/libs/badge-constructor/collection.json
  src/libs/role-constructor/collection.json
Labels: кухня

#1016 Добавляет страницу подписки и настройки рассылки
  src/scripts/index.js
  src/scripts/modules/subscribe-form.js
  src/styles/blocks/subscribe-page.css
  src/styles/index.css
  src/views/subscribe.11tydata.js
  src/views/subscribe.njk
Labels: кухня, вёрстка

#1015 Добавляет попап подписки
  src/includes/subscribe-popup.njk
  src/scripts/index.js
  src/scripts/modules/subscribe-popup.js
  src/styles/base-colors.css
  src/styles/blocks/subscribe-popup.css
  src/styles/dark-theme.css
  src/styles/index.css
  src/views/index.njk
Labels: кухня, вёрстка

#1044 Чинит шаблон врезки вопроса для интервью
  src/includes/questions.njk
Labels: вёрстка
