Repository doka-guide/platform, pull requests merged in 2023-07, with the labels that each got.

#1164 Добавляет ссылку на пятую главу
  src/images/letter.svg
  src/views/index.njk
Labels: вёрстка

#1167 Исправляет ссылки в футере
  src/includes/blocks/footer.njk
Labels: ошибка

#1168 Добавляет промо стрима про резюме на главную
  src/includes/blocks/promo.njk
  src/views/index.njk
Labels: улучшение, вёрстка

#1169 Убирает промо с главной
  src/views/index.njk
Labels: вёрстка
