Repository doka-guide/platform, pull requests merged in 2023-12, with the labels that each got.

#1214 Удаляет дискорд
  README.md
  src/includes/blocks/footer.njk
Labels: кухня

#1215 Добавляет значок «Трудоголик»
  src/images/badges/ny.svg
  src/libs/badge-constructor/collection.json
Labels: дизайн

#1216 Добавляет клич о поиске и анонс собеседования
  src/promos/interview-promo.md
  src/promos/interview-search.md
Labels: промо

#1220 Обновляет модуль со списком браузеров
  package-lock.json
Labels: кухня

#1221 Добавляет промо со сбором вопросов
  src/promos/oklich-questions.md
Labels: промо

#1222 Первая серия изменений PWA
  src/sw.js
Labels: ошибка, кухня

#1226 Поправляет выравнивание заголовка фидбэк-формы
  src/styles/blocks/feedback-form.css
Labels: улучшение, вёрстка, дизайн

#1224 Вторая порция правок PWA
  src/sw.js
Labels: улучшение, кухня

#1229 Чинит промо под новую версию 11ty
  src/views/index.11tydata.js
Labels: ошибка, кухня

#1230 Хот-фикс для новой версии (практики и интервью)
  .eleventy.js
  src/views/doc.11tydata.js
Labels: ошибка, кухня, движок

#1227 Добавляет RSS-фид
  .eleventy.js
  package-lock.json
  src/scripts/core/base-component.js
  src/scripts/libs/__tests__/toc-text-crop-test.js
  src/scripts/modules/cookie-notification.js
  src/scripts/modules/feedback-form.js
  src/scripts/modules/header.js
  src/scripts/modules/logo.js
  src/scripts/modules/question-form.js
  src/scripts/modules/quick-search.js
  src/scripts/modules/search.js
  src/scripts/modules/subscribe-form.js
  src/scripts/modules/toc.js
  src/scripts/modules/triggers.js
  src/styles/blocks/article-image.css
  src/styles/blocks/article-nav.css
  src/styles/blocks/article.css
  src/styles/blocks/articles-group.css
  src/styles/blocks/baseline.css
  src/styles/blocks/block-code.css
  src/styles/blocks/content.css
  src/styles/blocks/featured-article.css
  src/styles/blocks/feedback-form.css
  src/styles/blocks/filter-panel.css
  src/styles/blocks/font-theme.css
  src/styles/blocks/header.css
  src/styles/blocks/index-block.css
  src/styles/blocks/index-section.css
  src/styles/blocks/linked-article.css
  src/styles/blocks/menu-toggle.css
  src/styles/blocks/nav-list.css
  src/styles/blocks/person-links-list.css
  src/styles/blocks/person-page.css
  src/styles/blocks/question-form.css
  src/styles/blocks/search-hit.css
  src/styles/blocks/search-page.css
  src/styles/blocks/switch.css
  src/styles/dark-theme.css
  src/styles/index.css
  src/styles/index.sc.css
  src/sw.js
  src/transforms/headings-anchor-transform.js
  src/transforms/headings-id-transform.js
  src/transforms/toc-transform.js
  src/views/doc.11tydata.js
  src/views/feed.11tydata.js
  src/views/feed.njk
  src/views/sitemap.11tydata.js
  src/views/views.11tydata.js
Labels: улучшение, кухня
