Repository doka-guide/platform, pull requests merged in 2023-08, with the labels that each got.

#1184 Добавляет отступы для блока с рекомендуемыми статьями
  src/styles/blocks/doc.css
Labels: вёрстка, дизайн

#1185 Добавляет правильный шрифт для `<kbd>`
  src/styles/blocks/content.css
Labels: улучшение, вёрстка, дизайн

#1182 Улучшает контрастность клавиатурных сокращений
  src/styles/blocks/hotkey.css
  src/styles/blocks/linked-article.css
Labels: ошибка, дизайн, доступность

#1187 Улучшает блок с Baseline
  src/includes/blocks/baseline.njk
  src/styles/blocks/baseline.css
Labels: улучшение, вёрстка, дизайн

#1192 Меняет вывод советов/ответов на странице автора
  src/views/person.11tydata.js
Labels: ошибка, движок

#1183 Разбирается с ориентирами страницы материала
  src/includes/blocks/linked-article.njk
  src/libs/heading-hierarchy/heading-hierarchy.js
  src/views/doc.njk
Labels: улучшение, вёрстка, доступность

#1193 Добавляет ссылку в профиль пользователя
  src/views/person.njk
Labels: улучшение

#1194 Исправляет агрегатор и вывод на странице участника
  src/views/person.11tydata.js
  src/views/person.njk
  src/views/views.11tydata.js
Labels: ошибка

#1197 Добавляет вывод практики и ответов без статей
  src/views/person.11tydata.js
Labels: ошибка
