Repository doka-guide/platform, pull requests merged in 2023-02, with the labels that each got.

#1098 Добавляет babel-jest
  .babelrc
  jest.config.js
  package-lock.json
  package.json
  src/scripts/modules/toc-text-crop.js
Labels: улучшение, кухня

#1101 Разбирается с `alt` на странице всех участников
  src/includes/blocks/person-avatar.njk
Labels: ошибка, вёрстка, доступность

#1100 Улучшает разметку фильтров по разделам (поиск)
  src/includes/blocks/search-category.njk
Labels: улучшение, вёрстка, доступность

#1061 Добавляет сообщение об успешном копировании ссылки
  src/scripts/modules/toc.js
  src/styles/blocks/article-heading.css
  src/styles/blocks/doc.css
  src/transforms/headings-anchor-transform.js
  src/views/doc.njk
Labels: улучшение, вёрстка, дизайн

#1103 Устраняет горизонтальный скролл на странице поиска
  src/styles/blocks/search-hit.css
Labels: ошибка, вёрстка, доступность

#1104 Улучшает сообщение о скопированном коде
  src/scripts/modules/copy-code-snippet.js
  src/transforms/article-code-blocks-transform.js
Labels: ошибка, вёрстка, доступность

#1099 Добавляет базовое описание архитектуры Платформы
  docs/README.md
  docs/how-its-work.md
Labels: улучшение, кухня
