Repository doka-guide/platform, pull requests merged in 2023-03, with the labels that each got.

#1112 Меняет клавиши навигации
  src/includes/blocks/linked-article.njk
  src/scripts/modules/linked-article-navigation.js
Labels: улучшение, вёрстка, дизайн

#1119 Добавляет альт в аватарку при его наличии
  src/includes/blocks/person-avatar.njk
  src/views/person.11tydata.js
  src/views/person.njk
Labels: кухня, движок, доступность

#1120 Возвращает ссылку на горящий бэклог на главную
  .env.example
  src/views/index.njk
Labels: улучшение, вёрстка

#1122 Исправляет фокус после копировании ссылки на раздел
  src/scripts/modules/toc.js
Labels: ошибка, доступность
