Repository doka-guide/platform, pull requests merged in 2023-01, with the labels that each got.

#1083 Добавил alt для логотипа Практикума на главной странице #1051
  src/views/index.njk
Labels: ошибка, вёрстка, доступность

#1084 Убрал избыточный aria-hidden из блока с избранными статьями #1052
  src/includes/blocks/featured-article.njk
Labels: улучшение, вёрстка, доступность

#1088 Добавляет `<h1>` на страницу всех участников
  src/views/people.njk
Labels: ошибка, вёрстка, доступность

#1094 Решает проблему сборки с падение по таймауту
  src/libs/github-contribution-service/github-contribution-service.js
Labels: ошибка, кухня, движок

#1096 Меняет порядок разделов
  .env.example
  config/constants.js
Labels: кухня

#1097 Чинит скрипт для открытия меню с фильтрами (участники, поиск)
  src/scripts/modules/filter-panel.js
  src/scripts/modules/search-page-filter.js
Labels: ошибка
