Repository doka-guide/platform, pull requests merged in 2023-09, with the labels that each got.

#1200 Добавляет промо на главную
  src/includes/blocks/promo.njk
  src/views/index.njk
Labels: вёрстка

#1196 Исправляет проблему медленной и постоянной анимации фиксированной шапки при скролле.
  src/scripts/modules/header.js
  src/styles/blocks/article.css
  src/styles/blocks/header.css
Labels: улучшение, дизайн

#1186 Улучшает кнопки для оценки материала
  src/includes/feedback-form.njk
  src/scripts/modules/feedback-form.js
  src/styles/blocks/feedback-form.css
  src/styles/blocks/text-control.css
  src/styles/blocks/vote.css
Labels: ошибка, вёрстка, дизайн, доступность

#1188 Улучшает форму подписки на рассылку
  src/scripts/modules/subscribe-form.js
  src/styles/blocks/subscribe-page.css
  src/transforms/headings-anchor-transform.js
  src/views/subscribe.njk
Labels: ошибка, вёрстка, дизайн, доступность

#1162 Добавляет выгрузку сокращённых док всего раздела
  src/views/article-index-json.11tydata.js
  src/views/article-index-json.njk
Labels: улучшение, кухня

#1201 Добавляет новый баннер на главную
  src/includes/blocks/promo-stream.njk
  src/views/index.njk
Labels: вёрстка

#1202 Убирает баннер стрима с главной
  src/views/index.njk
Labels: вёрстка
