Repository doka-guide/platform, pull requests merged in 2023-04, with the labels that each got.

#1128 Добавляет пространство к иконке карандаша
  src/styles/blocks/articles-group.css
Labels: улучшение, вёрстка, дизайн

#1127 Правит цвета в тёмной теме
  src/styles/blocks/subscribe-popup.css
  src/styles/dark-theme.css
  src/styles/light-theme.css
Labels: улучшение, вёрстка, дизайн

#1114 Добавляет скрипт с триггерами для показа попапа с рассылкой
  src/scripts/index.js
  src/scripts/modules/triggers.js
  src/styles/blocks/subscribe-popup.css
  src/views/article-index.njk
  src/views/doc.njk
  src/views/page.njk
  src/views/people.njk
  src/views/person.njk
Labels: улучшение, кухня

#1126 Восстанавливает фокус после копирования ссылки
  src/scripts/modules/toc.js
Labels: ошибка, улучшение, вёрстка

#1116 Добавляет live region и правильные заголовки на страницу поиска
  src/includes/blocks/search.njk
  src/scripts/modules/search.js
  src/views/search.njk
Labels: ошибка, улучшение, вёрстка, доступность

#1109 Исправляет поведение меню на главной
  src/includes/blocks/header.njk
  src/scripts/modules/header.js
  src/styles/blocks/header.css
  src/views/index.njk
Labels: улучшение, вёрстка, дизайн

#1131 Убираем текст в начале раздела «На собеседовании»
  src/includes/questions.njk
  src/styles/blocks/answer.css
  src/styles/blocks/questions.css
Labels: улучшение, вопрос

#1137 Добавляет заголовок новой главы
  src/styles/landing.css
  src/views/index.njk
Labels: улучшение, вёрстка

#1139 Правит разметку главной лендоса по трудоуйстройству
  src/images/stages.svg
  src/styles/landing.css
  src/views/index.njk
Labels: улучшение, вёрстка, дизайн

#1141 Правит ссылки в подвале
  config/constants.js
  src/includes/blocks/footer.njk
Labels: ошибка, улучшение, кухня
