Repository doka-guide/platform, pull requests merged in 2023-05, with the labels that each got.

#1142 Приносит виджет Baseline
  .eleventy.js
  package-lock.json
  package.json
  src/includes/blocks/baseline.njk
  src/styles/blocks/baseline.css
  src/styles/index.css
  src/views/doc.11tydata.js
  src/views/doc.njk
Labels: улучшение, вёрстка

#1140 Добавляет кнопки в раздел "Собеседование"
  src/includes/questions.njk
  src/styles/blocks/questions.css
Labels: улучшение, вёрстка

#1132 Добавляет тест модуля `last-update`
  src/scripts/libs/__tests__/last-update-test.js
  src/scripts/modules/last-update.js
Labels: кухня, движок

#1144 Добавляет ссылку на третью главу
  src/images/cv.svg
  src/views/index.njk
Labels: вёрстка

#1145 Fix: убирает отступ в лого на 404 странице
  src/styles/blocks/logo.css
Labels: улучшение, вёрстка

#1147 Меняет язык с человеческого на понятный
  src/views/index.11tydata.js
  src/views/index.njk
Labels: улучшение, кухня

#1148 Улучшает контрастность цветов в примерах кода
  src/styles/code-dark-theme.css
  src/styles/code-light-theme.css
Labels: ошибка, вёрстка, дизайн, доступность
