Repository doka-guide/platform, pull requests merged in 2023-06, with the labels that each got.

#1151 Делает `id` у кнопки копирования секции уникальным и изменяет её текст
  src/transforms/headings-anchor-transform.js
Labels: ошибка, вёрстка, доступность

#1152 Добавляет `aria-labelledby` для `<aside>` на странице материала
  src/includes/blocks/linked-article.njk
  src/views/doc.njk
Labels: ошибка, вёрстка, доступность

#1157 Исправляет опечатку
  src/styles/blocks/switch.css
Labels: ошибка, вёрстка

#1160 Добавляет значок Суперстар
  src/images/badges/hackathon-practicum.svg
  src/images/badges/superstar.svg
  src/libs/badge-constructor/collection.json
Labels: кухня

#1161 Новый футер
  src/includes/blocks/footer.njk
  src/styles/blocks/doc.css
  src/styles/blocks/footer.css
  src/styles/blocks/index-block.css
  src/styles/blocks/person-page.css
  src/styles/blocks/search-page.css
  src/styles/blocks/search-tag.css
  src/styles/blocks/standalone-page.css
  src/views/article-index.njk
  src/views/doc.njk
  src/views/person.njk
  src/views/search.njk
Labels: вёрстка
