Repository doka-guide/platform, pull requests merged in 2024-09, with the labels that each got.

#1293 Исправляет разметку списка ответов на странице участника
  src/views/person.njk
Labels: ошибка, вёрстка

#1302 Меняет партнёрский блок
  src/styles/blocks/intro.css
  src/views/index.njk
Labels: кухня

#1303 Корректирует определение 'длинного' совета
  src/views/doc.11tydata.js
Labels: улучшение

#1307 Добавляет кнопку со звёздочками GH в футер
  src/includes/blocks/footer.njk
  src/includes/meta.njk
Labels: улучшение

#1310 Чинит страницу участника
  src/styles/blocks/person-page.css
Labels: ошибка, вёрстка

#1288 Корректирует отображение эмодзи в breadcrumbs
  src/styles/blocks/breadcrumbs.css
  src/styles/blocks/header.css
Labels: ошибка
