Repository doka-guide/platform, pull requests merged in 2024-02, with the labels that each got.

#1235 Удаляет опцию про трудоустройство на странице подписки на рассылку
  src/views/subscribe.njk
Labels: улучшение, вёрстка

#1170 Рестайлинг рубрики "На собесе"
  .github/workflows/pr-preview.yml
  src/includes/practices.njk
  src/styles/blocks/answer.css
  src/styles/blocks/article-heading.css
  src/styles/blocks/practices.css
  src/styles/blocks/questions.css
Labels: улучшение, дизайн

#1240 Добавляет промо про стрим трудоустройства за границей
  src/promos/border-job.md
Labels: промо
