Repository doka-guide/platform, pull requests merged in 2024-05, with the labels that each got.

#1261 Чинит оформление ссылок на главной
  src/styles/blocks/footer.css
  src/styles/blocks/link.css
Labels: вёрстка

#1262 Чинит валидацию W3С
  .github/workflows/w3c-validator.yml
  src/views/views.11tydata.js
Labels: ошибка, кухня, автоматизация

#1264 Расширяет область клика у карточки
  src/styles/blocks/featured-article.css
  src/styles/blocks/link.css
Labels: улучшение, вёрстка
