Repository doka-guide/platform, pull requests merged in 2024-06, with the labels that each got.

#1270 Прячет невидимый заголовок разделов надёжнее
  src/styles/blocks/index-block.css
Labels: ошибка, вёрстка

#1273 Поднимает версию web-features
  package-lock.json
  package.json
Labels: улучшение, кухня

#1272 Исправляет ошибку в RSS-фиде
  .eleventy.js
Labels: ошибка
