Repository doka-guide/platform, pull requests merged in 2024-03, with the labels that each got.

#1247 Добавляет промо для стрима про алгоритмы
  src/promos/algos-after.md
  src/promos/algos.md
Labels: промо

#1251 Добавляет промо стрима про выгорание
  src/promos/burnout.md
Labels: промо

#1250 Добавляет баннер вверх сайта. Ссылка на исследование
  src/images/top-banner/bat-eyes.svg
  src/images/top-banner/bat-teeth.svg
  src/includes/blocks/top-banner.njk
  src/layouts/base.njk
  src/scripts/index.js
  src/scripts/modules/top-banner.js
  src/styles/blocks/top-banner.css
  src/styles/index.css
  src/sw.js
  src/views/article-index.njk
  src/views/doc.njk
  src/views/index.njk
  src/views/page.njk
  src/views/people.njk
  src/views/person.njk
Labels: кухня, вёрстка

#1248 Добавляет памяти
  package.json
Labels: ошибка
