Repository doka-guide/platform, pull requests merged in 2024-08, with the labels that each got.

#1279 Поднимает версию web-features до 1.0.0
  .eleventy.js
  package-lock.json
  package.json
Labels: улучшение, автоматизация

#1285 Меняет цвет svg-файвиконки под тему в ОС
  src/images/icons/icon.svg
Labels: улучшение

#1283 Прибивает подвал
  src/styles/blocks/base.css
Labels: вёрстка

#1291 Упрощает получение значение свойства `article.data.cover.mobile`
  src/scripts/modules/transform-article-data.js
Labels: улучшение

#1299 Фиксирует меню так, чтобы всё работало как надо
  src/styles/blocks/header.css
Labels: ошибка, вёрстка

#1300 Исправляет обработку перехода к поиску по клавише '/'
  src/scripts/modules/header.js
  src/scripts/modules/search.js
Labels: ошибка
